# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rembot.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1653, 1160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        Main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        Main.setLayoutDirection(QtCore.Qt.LeftToRight)
        Main.setStyleSheet("")
        
        self.Rembot = QtWidgets.QWidget(Main)
        self.Rembot.setEnabled(True)
        self.Rembot.setAutoFillBackground(False)
        self.Rembot.setObjectName("Rembot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Rembot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_box = QtWidgets.QHBoxLayout()
        self.title_box.setContentsMargins(10, 10, 10, 10)
        self.title_box.setObjectName("title_box")
        self.prgoram_title = QtWidgets.QLabel(self.Rembot)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.prgoram_title.setFont(font)
        self.prgoram_title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.prgoram_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prgoram_title.setStyleSheet("color: rgb(108, 204, 227);")
        self.prgoram_title.setScaledContents(False)
        self.prgoram_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.prgoram_title.setContentsMargins(0, 0, 0, 0)
        self.prgoram_title.setObjectName("prgoram_title")
        self.title_box.addWidget(self.prgoram_title)
        self.version_number = QtWidgets.QLabel(self.Rembot)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_number.setFont(font)
        self.version_number.setStyleSheet("color: rgb(85, 85, 85);")
        self.version_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_number.setObjectName("version_number")
        self.title_box.addWidget(self.version_number)        
        self.verticalLayout.addLayout(self.title_box)


        self.content_box = QtWidgets.QHBoxLayout()
        self.content_box.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.content_box.setContentsMargins(10, 10, 10, 10)
        self.content_box.setObjectName("content_box")

        self.left_box = QtWidgets.QVBoxLayout()
        self.left_box.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.left_box.setContentsMargins(10, 10, 10, 10)
        self.left_box.setObjectName("left_box")
        self.file_box = QtWidgets.QHBoxLayout()
        self.file_box.setContentsMargins(10, 10, 10, 10)
        self.file_box.setObjectName("file_box")
        self.label = QtWidgets.QLabel(self.Rembot)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.file_box.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.Rembot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.file_box.addWidget(self.lineEdit)
        self.left_box.addLayout(self.file_box)

        self.button_box = QtWidgets.QGridLayout()
        self.button_box.setContentsMargins(10, 10, 10, 10)
        self.button_box.setObjectName("button_box")
        self.start_button = QtWidgets.QPushButton(self.Rembot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")

        self.button_box.addWidget(self.start_button, 0, 0, 1, 1)

        self.stop_button = QtWidgets.QPushButton(self.Rembot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")

        self.button_box.addWidget(self.stop_button, 0, 1, 1, 1)

        self.test_button = QtWidgets.QPushButton(self.Rembot)
        self.test_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_button.sizePolicy().hasHeightForWidth())
        self.test_button.setSizePolicy(sizePolicy)
        self.test_button.setObjectName("test_button")

        self.button_box.addWidget(self.test_button, 1, 0, 1, 1)

        self.quit_button = QtWidgets.QPushButton(self.Rembot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_button.sizePolicy().hasHeightForWidth())
        self.quit_button.setSizePolicy(sizePolicy)
        self.quit_button.setObjectName("quit_button")

        self.button_box.addWidget(self.quit_button, 1, 1, 1, 1)

        self.left_box.addLayout(self.button_box)

        self.log_box = QtWidgets.QGroupBox(self.Rembot)
        self.log_box.setFlat(True)
        self.log_box.setObjectName("log_box")
        self.log_layout = QtWidgets.QVBoxLayout(self.log_box)
        self.log_layout.setContentsMargins(0, 10, 0, 0)
        self.log_layout.setObjectName("log_layout")
        self.textBrowser = QtWidgets.QTextBrowser(self.log_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.log_layout.addWidget(self.textBrowser)
        self.left_box.addWidget(self.log_box)
        self.content_box.addLayout(self.left_box)

        self.right_box = QtWidgets.QVBoxLayout()
        self.right_box.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.right_box.setContentsMargins(10, 10, 10, 10)
        self.right_box.setObjectName("right_box")
        self.original_img_box = QtWidgets.QGroupBox(self.Rembot)
        self.original_img_box.setFlat(True)
        self.original_img_box.setObjectName("original_img_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.original_img_box)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.original_img = QtWidgets.QLabel(self.original_img_box)
        self.original_img.setText("")
        self.original_img.setPixmap(QtGui.QPixmap("BlackBox.jpg"))
        self.original_img.setScaledContents(True)
        self.original_img.setObjectName("original_img")

        self.verticalLayout_2.addWidget(self.original_img)

        self.right_box.addWidget(self.original_img_box)
        
        self.output_img_box = QtWidgets.QGroupBox(self.Rembot)
        self.output_img_box.setFlat(True)
        self.output_img_box.setObjectName("output_img_box")
        self.output_img_box_2 = QtWidgets.QHBoxLayout(self.output_img_box)
        self.output_img_box_2.setContentsMargins(0, 0, 0, 0)
        self.output_img_box_2.setObjectName("output_img_box_2")
        self.label_2 = QtWidgets.QLabel(self.output_img_box)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("BlackBox.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.output_img_box_2.addWidget(self.label_2)
        self.right_box.addWidget(self.output_img_box)
        self.content_box.addLayout(self.right_box)
        self.verticalLayout.addLayout(self.content_box)
        
        Main.setCentralWidget(self.Rembot)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1653, 38))
        self.menuBar.setObjectName("menuBar")
        self.about = QtWidgets.QMenu(self.menuBar)
        self.about.setObjectName("about")
        Main.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.about.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Rembot"))
        self.prgoram_title.setText(_translate("Main", "REMBOT"))
        self.version_number.setText(_translate("Main", "v0.0.1"))
        self.label.setText(_translate("Main", "File name"))
        self.lineEdit.setPlaceholderText(_translate("Main", "image.ext"))
        self.start_button.setText(_translate("Main", "START"))
        self.stop_button.setText(_translate("Main", "STOP"))
        self.test_button.setText(_translate("Main", "TEST"))
        self.quit_button.setText(_translate("Main", "QUIT"))
        self.log_box.setTitle(_translate("Main", "Log"))
        self.original_img_box.setTitle(_translate("Main", "Original Image"))
        self.output_img_box.setTitle(_translate("Main", "Output Image"))
        self.about.setTitle(_translate("Main", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

