# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rembot.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.resize(1687, 1159)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainUI.sizePolicy().hasHeightForWidth())
        MainUI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        MainUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainUI.setWindowIcon(icon)
        MainUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainUI.setStyleSheet("")
        self.RembotUI = QtWidgets.QWidget(MainUI)
        self.RembotUI.setEnabled(True)
        self.RembotUI.setAutoFillBackground(False)
        self.RembotUI.setObjectName("RembotUI")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RembotUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_box = QtWidgets.QHBoxLayout()
        self.title_box.setContentsMargins(10, 10, 10, 10)
        self.title_box.setObjectName("title_box")
        self.prgoram_title = QtWidgets.QLabel(self.RembotUI)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.prgoram_title.setFont(font)
        self.prgoram_title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.prgoram_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prgoram_title.setStyleSheet("color: rgb(108, 204, 227);")
        self.prgoram_title.setScaledContents(False)
        self.prgoram_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.prgoram_title.setContentsMargins(0, 0, 0, 0)
        self.prgoram_title.setObjectName("prgoram_title")
        self.title_box.addWidget(self.prgoram_title)
        self.version_number = QtWidgets.QLabel(self.RembotUI)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_number.setFont(font)
        self.version_number.setStyleSheet("color: rgb(85, 85, 85);")
        self.version_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_number.setObjectName("version_number")
        self.title_box.addWidget(self.version_number)
        self.verticalLayout.addLayout(self.title_box)
        self.content_box = QtWidgets.QHBoxLayout()
        self.content_box.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.content_box.setContentsMargins(10, 10, 10, 10)
        self.content_box.setObjectName("content_box")
        self.left_box = QtWidgets.QVBoxLayout()
        self.left_box.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.left_box.setContentsMargins(10, 10, 10, 10)
        self.left_box.setObjectName("left_box")
        self.file_box = QtWidgets.QHBoxLayout()
        self.file_box.setContentsMargins(10, 10, 10, 10)
        self.file_box.setObjectName("file_box")
        self.file_label = QtWidgets.QLabel(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_label.sizePolicy().hasHeightForWidth())
        self.file_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_label.setFont(font)
        self.file_label.setObjectName("file_label")
        self.file_box.addWidget(self.file_label)
        self.file_input = QtWidgets.QLineEdit(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_input.sizePolicy().hasHeightForWidth())
        self.file_input.setSizePolicy(sizePolicy)
        self.file_input.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.file_input.setFont(font)
        self.file_input.setAcceptDrops(True)
        self.file_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.file_input.setText("")
        self.file_input.setFrame(True)
        self.file_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.file_input.setObjectName("file_input")
        self.file_box.addWidget(self.file_input)
        self.left_box.addLayout(self.file_box)
        self.button_box = QtWidgets.QGridLayout()
        self.button_box.setContentsMargins(10, 10, 10, 10)
        self.button_box.setObjectName("button_box")
        self.start_button = QtWidgets.QPushButton(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")
        self.button_box.addWidget(self.start_button, 0, 0, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.button_box.addWidget(self.stop_button, 0, 1, 1, 1)
        self.test_button = QtWidgets.QPushButton(self.RembotUI)
        self.test_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_button.sizePolicy().hasHeightForWidth())
        self.test_button.setSizePolicy(sizePolicy)
        self.test_button.setObjectName("test_button")
        self.button_box.addWidget(self.test_button, 1, 0, 1, 1)
        self.quit_button = QtWidgets.QPushButton(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_button.sizePolicy().hasHeightForWidth())
        self.quit_button.setSizePolicy(sizePolicy)
        self.quit_button.setObjectName("quit_button")
        self.button_box.addWidget(self.quit_button, 1, 1, 1, 1)
        self.left_box.addLayout(self.button_box)
        self.log_box = QtWidgets.QGroupBox(self.RembotUI)
        self.log_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_box.sizePolicy().hasHeightForWidth())
        self.log_box.setSizePolicy(sizePolicy)
        self.log_box.setFlat(True)
        self.log_box.setCheckable(False)
        self.log_box.setObjectName("log_box")
        self.log_layout = QtWidgets.QVBoxLayout(self.log_box)
        self.log_layout.setContentsMargins(0, 10, 0, 0)
        self.log_layout.setObjectName("log_layout")
        self.left_box.addWidget(self.log_box)
        self.log_output = QtWidgets.QTextEdit(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.log_output.sizePolicy().hasHeightForWidth())
        self.log_output.setSizePolicy(sizePolicy)
        self.log_output.setMinimumSize(QtCore.QSize(0, 0))
        self.log_output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.log_output.setReadOnly(True)
        self.log_output.setObjectName("log_output")
        self.left_box.addWidget(self.log_output)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.left_box.addItem(spacerItem)
        self.content_box.addLayout(self.left_box)
        self.right_box = QtWidgets.QVBoxLayout()
        self.right_box.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.right_box.setContentsMargins(10, 10, 10, 10)
        self.right_box.setObjectName("right_box")
        self.original_img_box = QtWidgets.QGroupBox(self.RembotUI)
        self.original_img_box.setFlat(True)
        self.original_img_box.setObjectName("original_img_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.original_img_box)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.original_img = QtWidgets.QLabel(self.original_img_box)
        self.original_img.setMinimumSize(QtCore.QSize(720, 400))
        self.original_img.setText("")
        self.original_img.setPixmap(QtGui.QPixmap("default.jpg"))
        self.original_img.setScaledContents(True)
        self.original_img.setObjectName("original_img")
        self.verticalLayout_2.addWidget(self.original_img)
        self.right_box.addWidget(self.original_img_box)
        self.output_img_box = QtWidgets.QGroupBox(self.RembotUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_img_box.sizePolicy().hasHeightForWidth())
        self.output_img_box.setSizePolicy(sizePolicy)
        self.output_img_box.setFlat(True)
        self.output_img_box.setObjectName("output_img_box")
        self.output_img_box_2 = QtWidgets.QHBoxLayout(self.output_img_box)
        self.output_img_box_2.setContentsMargins(0, 0, 0, 0)
        self.output_img_box_2.setObjectName("output_img_box_2")
        self.output_img = QtWidgets.QLabel(self.output_img_box)
        self.output_img.setMinimumSize(QtCore.QSize(720, 400))
        self.output_img.setText("")
        self.output_img.setPixmap(QtGui.QPixmap("default.jpg"))
        self.output_img.setScaledContents(True)
        self.output_img.setObjectName("output_img")
        self.output_img_box_2.addWidget(self.output_img)
        self.right_box.addWidget(self.output_img_box)
        self.content_box.addLayout(self.right_box)
        self.verticalLayout.addLayout(self.content_box)
        MainUI.setCentralWidget(self.RembotUI)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1687, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.rembot_menu = QtWidgets.QMenu(self.menubar)
        self.rembot_menu.setObjectName("rembot_menu")
        self.menuView = QtWidgets.QMenu(self.rembot_menu)
        self.menuView.setObjectName("menuView")
        MainUI.setMenuBar(self.menubar)
        self.action_exit = QtWidgets.QAction(MainUI)
        self.action_exit.setObjectName("action_exit")
        self.action_about = QtWidgets.QAction(MainUI)
        self.action_about.setObjectName("action_about")
        self.action_log = QtWidgets.QAction(MainUI)
        self.action_log.setCheckable(True)
        self.action_log.setChecked(True)
        self.action_log.setObjectName("action_log")
        self.menuView.addAction(self.action_log)
        self.rembot_menu.addAction(self.action_about)
        self.rembot_menu.addAction(self.menuView.menuAction())
        self.rembot_menu.addSeparator()
        self.rembot_menu.addAction(self.action_exit)
        self.menubar.addAction(self.rembot_menu.menuAction())

        self.retranslateUi(MainUI)
        self.action_exit.triggered.connect(MainUI.close)
        self.start_button.clicked.connect(self.RembotUI.update)
        self.quit_button.clicked.connect(MainUI.close)
        self.stop_button.clicked.connect(self.RembotUI.update)
        self.action_log.toggled['bool'].connect(self.log_box.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "Rembot"))
        self.prgoram_title.setText(_translate("MainUI", "REMBOT"))
        self.version_number.setText(_translate("MainUI", "v0.0.1"))
        self.file_label.setText(_translate("MainUI", "File name"))
        self.file_input.setPlaceholderText(_translate("MainUI", "image.png"))
        self.start_button.setText(_translate("MainUI", "START"))
        self.stop_button.setText(_translate("MainUI", "STOP"))
        self.test_button.setText(_translate("MainUI", "TEST"))
        self.quit_button.setText(_translate("MainUI", "QUIT"))
        self.log_box.setTitle(_translate("MainUI", "Log"))
        self.original_img_box.setTitle(_translate("MainUI", "Original Image"))
        self.output_img_box.setTitle(_translate("MainUI", "Output Image"))
        self.rembot_menu.setTitle(_translate("MainUI", "Rembot"))
        self.menuView.setTitle(_translate("MainUI", "View"))
        self.action_exit.setText(_translate("MainUI", "Exit"))
        self.action_exit.setShortcut(_translate("MainUI", "Ctrl+Q"))
        self.action_about.setText(_translate("MainUI", "About"))
        self.action_about.setShortcut(_translate("MainUI", "Ctrl+A"))
        self.action_log.setText(_translate("MainUI", "Log"))
        self.action_log.setShortcut(_translate("MainUI", "Ctrl+L"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUI = QtWidgets.QMainWindow()
    ui = Ui_MainUI()
    ui.setupUi(MainUI)
    MainUI.show()
    sys.exit(app.exec_())

